import { collection, addDoc, serverTimestamp } from "firebase/firestore";
import { db } from "./firebase";

export const SAMPLE_CASES = [
  // Zona Merah
  {
    zona: "merah",
    triageResult: "MERAH",
    jalur: "verbal",
    type: "VERBAL",
    relawanName: "Ahmad Fauzi",
    volunteerName: "Ahmad Fauzi",
    poskoName: "Posko Utama - Kota",
    poskoLat: -6.2088,
    poskoLng: 106.8456,
    lat: -6.2088 + 0.003,
    lng: 106.8456 - 0.002,
    transcript:
      "Saya sudah tidak sanggup lagi, rumah dan keluarga hilang. Saya mau mati saja menyakiti diri, tidak ada gunanya hidup.",
    detectedKeywords: ["mau mati", "menyakiti diri", "tidak ada gunanya hidup"],
    keywords: ["mau mati", "menyakiti diri", "tidak ada gunanya hidup"],
    pfaShown: true,
    needsPFA: true,
    score: 3,
  },
  {
    zona: "merah",
    triageResult: "MERAH",
    jalur: "nonverbal",
    type: "NON_VERBAL",
    relawanName: "Siti Rahma",
    volunteerName: "Siti Rahma",
    poskoName: "Posko Barat - Tangerang",
    poskoLat: -6.1781,
    poskoLng: 106.6319,
    lat: -6.1781 - 0.002,
    lng: 106.6319 + 0.003,
    checklistAnswers: {
      q1: true, // histeria
      q2: false,
      q3: false,
      q4: true,
      q5: true,
      q6: false,
      q7: false,
      q8: false,
    },
    criticalItems: ["Histeria / menjerit tidak terkendali"],
    warningItems: [
      "Gemetar hebat / panik berlebihan",
      "Menangis terus-menerus",
    ],
    pfaShown: true,
    needsPFA: true,
    score: 3,
  },
  {
    zona: "merah",
    triageResult: "MERAH",
    jalur: "nonverbal",
    type: "NON_VERBAL",
    relawanName: "Budi Santoso",
    volunteerName: "Budi Santoso",
    poskoName: "Posko Timur - Bekasi",
    poskoLat: -6.2383,
    poskoLng: 106.9756,
    lat: -6.2383 + 0.004,
    lng: 106.9756 + 0.001,
    checklistAnswers: {
      q1: false,
      q2: true, // disosiatif
      q3: true, // niat menyakiti diri
      q4: false,
      q5: false,
      q6: true,
      q7: true,
      q8: false,
    },
    criticalItems: [
      "Tidak merespons (disosiatif)",
      "Niat menyakiti diri sendiri",
    ],
    warningItems: ["Menolak makan/minum >24 jam", "Bingung / disorientasi"],
    pfaShown: true,
    needsPFA: true,
    score: 3,
  },
  // Zona Kuning
  {
    zona: "kuning",
    triageResult: "KUNING",
    jalur: "verbal",
    type: "VERBAL",
    relawanName: "Dewi Lestari",
    volunteerName: "Dewi Lestari",
    poskoName: "Posko Selatan - Depok",
    poskoLat: -6.4025,
    poskoLng: 106.7942,
    lat: -6.4025 + 0.002,
    lng: 106.7942 - 0.003,
    transcript:
      "Saya sangat takut dan cemas kalau ada gempa susulan. Semalam tidak bisa tidur sama sekali.",
    detectedKeywords: ["takut", "cemas", "tidak bisa tidur"],
    keywords: ["takut", "cemas", "tidak bisa tidur"],
    pfaShown: false,
    needsPFA: false,
    score: 2,
  },
  {
    zona: "kuning",
    triageResult: "KUNING",
    jalur: "verbal",
    type: "VERBAL",
    relawanName: "Ahmad Fauzi",
    volunteerName: "Ahmad Fauzi",
    poskoName: "Posko Utama - Kota",
    poskoLat: -6.2088,
    poskoLng: 106.8456,
    lat: -6.2088 - 0.004,
    lng: 106.8456 + 0.002,
    transcript:
      "Badan saya masih gemetar, rasanya panik terus dan bingung mau berbuat apa.",
    detectedKeywords: ["gemetar", "panik", "bingung"],
    keywords: ["gemetar", "panik", "bingung"],
    pfaShown: false,
    needsPFA: false,
    score: 2,
  },
  {
    zona: "kuning",
    triageResult: "KUNING",
    jalur: "nonverbal",
    type: "NON_VERBAL",
    relawanName: "Rian Pratama",
    volunteerName: "Rian Pratama",
    poskoName: "Posko Utara - Tangerang Selatan",
    poskoLat: -6.2894,
    poskoLng: 106.7108,
    lat: -6.2894 + 0.003,
    lng: 106.7108 + 0.002,
    checklistAnswers: {
      q1: false,
      q2: false,
      q3: false,
      q4: true,
      q5: true,
      q6: false,
      q7: true,
      q8: false,
    },
    criticalItems: [],
    warningItems: [
      "Gemetar hebat / panik berlebihan",
      "Menangis terus-menerus",
      "Bingung / disorientasi",
    ],
    pfaShown: false,
    needsPFA: false,
    score: 2,
  },
  {
    zona: "kuning",
    triageResult: "KUNING",
    jalur: "nonverbal",
    type: "NON_VERBAL",
    relawanName: "Siti Rahma",
    volunteerName: "Siti Rahma",
    poskoName: "Posko Barat - Tangerang",
    poskoLat: -6.1781,
    poskoLng: 106.6319,
    lat: -6.1781 + 0.004,
    lng: 106.6319 - 0.001,
    checklistAnswers: {
      q1: false,
      q2: false,
      q3: false,
      q4: false,
      q5: true,
      q6: true,
      q7: false,
      q8: false,
    },
    criticalItems: [],
    warningItems: ["Menangis terus-menerus", "Menolak makan/minum >24 jam"],
    pfaShown: false,
    needsPFA: false,
    score: 2,
  },
  // Zona Hijau
  {
    zona: "hijau",
    triageResult: "HIJAU",
    jalur: "verbal",
    type: "VERBAL",
    relawanName: "Budi Santoso",
    volunteerName: "Budi Santoso",
    poskoName: "Posko Timur - Bekasi",
    poskoLat: -6.2383,
    poskoLng: 106.9756,
    lat: -6.2383 - 0.002,
    lng: 106.9756 - 0.003,
    transcript:
      "Alhamdulillah kondisi kami sekeluarga aman dan tenang di tenda ini, bantuan makanan juga cukup.",
    detectedKeywords: [],
    keywords: [],
    pfaShown: false,
    needsPFA: false,
    score: 0,
  },
  {
    zona: "hijau",
    triageResult: "HIJAU",
    jalur: "nonverbal",
    type: "NON_VERBAL",
    relawanName: "Dewi Lestari",
    volunteerName: "Dewi Lestari",
    poskoName: "Posko Selatan - Depok",
    poskoLat: -6.4025,
    poskoLng: 106.7942,
    lat: -6.4025 - 0.001,
    lng: 106.7942 + 0.004,
    checklistAnswers: {
      q1: false,
      q2: false,
      q3: false,
      q4: false,
      q5: false,
      q6: false,
      q7: false,
      q8: true,
    },
    criticalItems: [],
    warningItems: [],
    pfaShown: false,
    needsPFA: false,
    score: 0,
  },
  {
    zona: "hijau",
    triageResult: "HIJAU",
    jalur: "verbal",
    type: "VERBAL",
    relawanName: "Rian Pratama",
    volunteerName: "Rian Pratama",
    poskoName: "Posko Utara - Tangerang Selatan",
    poskoLat: -6.2894,
    poskoLng: 106.7108,
    lat: -6.2894 - 0.002,
    lng: 106.7108 - 0.003,
    transcript:
      "Kami baik-baik saja dan bersyukur sudah dievakuasi ke posko ini.",
    detectedKeywords: [],
    keywords: [],
    pfaShown: false,
    needsPFA: false,
    score: 0,
  },
];

export async function seedDemoData() {
  const collectionRef = collection(db, "cases");
  const results = [];

  for (const item of SAMPLE_CASES) {
    const docRef = await addDoc(collectionRef, {
      ...item,
      createdAt: serverTimestamp(),
      timestamp: new Date().toISOString(),
      location: {
        lat: item.lat,
        lng: item.lng,
      },
      syncedFromOffline: false,
    });
    results.push(docRef.id);
  }

  return results;
}
